### ISSUE TITLE
Where to find input files 

### ISSUE THREAD

**Issue by kamwal** [euroargodev/DMQC_status_and_statistics#3]
I was trying to use the code to generate some statistic plots. However, I am not sure where I can find the inputs.
For the argo_profile_detailled_index.txt and ar_greylist.txt, I have found them on GDAC  (https://data-argo.ifremer.fr/)

 How about the float list? 

"- floats list: csv file, with in header WMO, RT (dac in charge of real time
% processing) and DM (institution in charge of delayed mode processing), 
% separated by ';'. Exemple: MOCCA_rt_dm.csv" 

 Should this list be generated by each DAC or by each country separate? Is there any shared code available to generate this list? Or I missed something?

**Comment by delphinedobler** [comment]
Hi Kamila,

with the help of @gmaze , I've just created the new v3.1 release. 
In this release, the input file content has changed a little, and is now detailed in the readme file. In addition, an example is accessible in the INPUT_examples directory (MOCCA.csv).

Delphine
